import { defineType, defineField, defineArrayMember } from "sanity";
import { LinkIcon, ArrowTopRightIcon } from '@sanity/icons'
import { lineageSteps } from "@/sanity/lib/lineage-steps";

const companies = [
  "1047 Games / Splitgate",
  "2K Sports / NBA 2K",
  "212 Performance Gloves",
  "ACD",
  "Adidas",
  "Advent Health",
  "Amazon",
  "Anvil",
  "AST Space Mobile",
  "ASUS",
  "AT&T",
  "Ateliere (Ownzones)",
  "Auntie Aloha",
  "Bally Sports",
  "BODYARMOR",
  "Bytedance",
  "Cameo",
  "Cargill",
  "Castle Building Centers",
  "CenturyLink",
  "Cheeky",
  "Choon / Emanate",
  "ClutchPoints",
  "Colorado Avalanche",
  "Colorado Rapids",
  "Comcast",
  "Conn's",
  "Core Water",
  "Cox",
  "Crackle",
  "Degree",
  "Denver Nuggets",
  "Detroit Red Wings",
  "DIRECTV",
  "Dollar Shave Club",
  "DPA",
  "Dyson",
  "Endicia",
  "Epson",
  "Eko (Clorox, Oreo, Nintendo)",
  "Essence Magazine",
  "EV Connect",
  "F45 Training",
  "Fabuloso",
  "Ferrari North America",
  "FIGS",
  "FitPlan",
  "Flexa",
  "Focus Brands (Cinnabon, Jamba Juice, etc.)",
  "Fox Sports",
  "FSRT",
  "2K Sports / NBA 2K",
  "212 Performance Gloves",
  "ACD",
  "Adidas",
  "Advent Health",
  "Amazon",
  "Anvil",
  "AST Space Mobile",
  "ASUS",
  "AT&T",
  "Ateliere (Ownzones)",
  "Auntie Aloha",
  "Bally Sports",
  "BODYARMOR",
  "Bytedance",
  "Cameo",
  "Cargill",
  "Castle Building Centers",
  "CenturyLink",
  "Cheeky",
  "Choon / Emanate",
  "ClutchPoints",
  "Colorado Avalanche",
  "Colorado Rapids",
  "Comcast",
  "Conn’s",
  "Core Water",
  "Cox",
  "Crackle",
  "Degree",
  "Denver Nuggets",
  "Detroit Red Wings",
  "DIRECTV",
  "Dollar Shave Club",
  "DPA",
  "Dyson",
  "Endicia",
  "Epson",
  "Eko (Clorox, Oreo, Nintendo)",
  "Essence Magazine",
  "EV Connect",
  "F45 Training",
  "Fabuloso",
  "Ferrari North America",
  "FIGS",
  "FitPlan",
  "Flexa",
  "Focus Brands (Cinnabon, Jamba Juice, etc.)",
  "Fox Sports",
  "FSRT",
  "FuboTV",
  "Gala Games",
  "Google",
  "Grainger",
  "Growth Factor",
  "GT’s Living Foods",
  "HBO",
  "Henkel",
  "High Brew Coffee",
  "Hudson’s Bay",
  "Human Rights Foundation",
  "IBM",
  "Inc. Magazine",
  "Incubate Coalition",
  "Insomniac Records",
  "Indiana Pacers",
  "Indiana Fever",
  "Instacart",
  "Kaiser Permanente",
  "Kia",
  "Konami",
  "KYOTCs",
  "Lavazza",
  "Los Angeles Kings",
  "Los Angeles Football Club",
  "Leaseplan",
  "Level3",
  "Limeade",
  "Lowe’s / Kobalt Tools",
  "Lumber Liquidators (LL Flooring)",
  "Marvel Snap",
  "Medable",
  "Mercedes-Benz",
  "Microsoft",
  "Miele",
  "Mighty Swell Cocktails",
  "MLBPA",
  "Momentum Solar",
  "Movember",
  "Myabetic",
  "National Action Network",
  "NBPA",
  "New Jersey Devils",
  "New York Knicks",
  "New York Rangers",
  "NewsCred",
  "NFLPA",
  "Niantic / Pokémon GO",
  "Neiman Marcus",
  "Nutpods",
  "Oracle",
  "Organic Initiative",
  "Parlux / Jason Wu",
  "People Magazine",
  "Planet Beauty",
  "Philip Morris International",
  "Por Osos",
  "Premier Skateboard Association",
  "PRFC",
  "PriceWaterhouseCoopers",
  "PrivacyGuard",
  "PrizePicks",
  "Procore",
  "PUBG (PlayerUnknown’s Battleground)",
  "RealSelf",
  "RHA Music Festival",
  "Riot Games",
  "Salesforce",
  "Sam’s Club",
  "Sanabul",
  "Scopely / Kingdom Maker",
  "SiFive",
  "Sinclair",
  "SiriusXM",
  "SMS Audio",
  "Spectrum",
  "Sports Illustrated",
  "Starz / Lionsgate",
  "Sunlife",
  "Survios",
  "Talking Rain Beverage Co",
  "The Hartford Insurance",
  "TTEC",
  "Turner Networks (TBS, TNT)",
  "Uber",
  "UCLA Health",
  "Under Armour",
  "United Technologies",
];



export default defineType({
  name: 'richTextPage',
  title: 'Rich Text (Page)',
  type: 'array',
  of: [
    defineArrayMember({
      type: 'block',
      styles: [
        { title: 'Normal', value: 'normal' },
        { title: 'Heading', value: 'h2' },
      ],
      marks: {
        decorators: [
          { title: 'Italic', value: 'em' },
          { title: 'Bold', value: 'strong' },
        ],
        annotations: [
          defineField({
            name: 'internalLink',
            title: 'Internal Link',
            type: 'object',
            fields: [
              defineField({
                name: 'to',
                title: 'To',
                type: 'reference',
                to: [
                  { type: 'homePage' },
                ]
              })
            ],
            icon: () => <LinkIcon />
          }),
          defineField({
            title: 'External Link',
            name: 'externalLink',
            type: 'object',
            fields: [
              defineField({
                name: 'url',
                title: 'URL',
                type: 'url',
                validation: (Rule) => Rule.uri({
                  allowRelative: true,
                  scheme: ['http', 'https', 'mailto', 'tel']
                })
              }),
            ],
            icon: () => <ArrowTopRightIcon />
          })
        ]
      },
    }),
    defineArrayMember({
      name: 'expandableList',
      title: 'Expandable List',
      type: 'object',
      fields: [
        defineField({
          name: 'title',
          title: 'Title',
          type: 'string',
        }),
        defineField({
          name: 'color',
          title: 'Color',
          type: 'string',
          options: {
            list: lineageSteps,
          },
          initialValue: 'one'
        }),
        defineField({
          name: 'items',
          title: 'Items',
          type: 'text',
          rows: 4,
          description: 'Each new line will be treated as a new item'
        })
      ]
    })
  ]
})